setup: Update charm-tools pin set
juju/charm-tools pull request #659
Opened 2023-07-20 19:53 UTC by coreycb

pyyaml 5.4.0 and 5.4.1 are broken with cython 3
https://github.com/yaml/pyyaml/issues/724

jsonschema 4.18.0 depends on Rust (via rpds-py)

2023-07-21 10:14 UTC, ajkavanagh commented
This is similar to #656 - could we please consolidate them?  So we also need to pin `Cython<3.0.0` as that's also broken with PyYaml 6.0.1 (at the moment).

2023-07-21 10:15 UTC, ajkavanagh requested changes
Do we also need to pin Cython?

2023-08-02 15:33 UTC, ajkavanagh approved these changes

2023-08-02 15:33 UTC, merged

2023-08-08 15:57 UTC, freyes commented
we need a 3.0.7 release in pypi with this fix

2023-08-09 19:58 UTC, markbeierl commented
This change should be revisited now that 6.0.1 was released to fix the problem.  I'm not sure, but it looks like the result of         'pyyaml>=5.0,!=5.4.0,!=5.4.1,<6.0' is 5.3.1, which has known CVEs.

```
pip install 'pyyaml>=5.0,!=5.4.0,!=5.4.1,<6.0'
Collecting pyyaml!=5.4.0,!=5.4.1,<6.0,>=5.0
  Using cached PyYAML-5.3.1-cp311-cp311-linux_x86_64.whl
Installing collected packages: pyyaml
Successfully installed pyyaml-5.3.1
```

2023-08-09 20:38 UTC, freyes commented
On Wed, 2023-08-09 at 12:58 -0700, Mark Beierl wrote:
> This change should be revisited now that 6.0.1 was released to fix the problem.  I'm not sure, but
> it looks like the result of         'pyyaml>=5.0,!=5.4.0,!=5.4.1,<6.0' is 5.3.1, which has known
> CVEs.
> pip install 'pyyaml>=5.0,!=5.4.0,!=5.4.1,<6.0'
> Collecting pyyaml!=5.4.0,!=5.4.1,<6.0,>=5.0
>   Using cached PyYAML-5.3.1-cp311-cp311-linux_x86_64.whl
> Installing collected packages: pyyaml
> Successfully installed pyyaml-5.3.1

I think we could do:

pyyaml>=5.0,!=5.4.0,!=5.4.1,!=6.0,<7.0

2023-08-09 20:48 UTC, freyes commented
https://github.com/juju/charm-tools/pull/663